sudo: required
services:
  - docker

before_install:
  - docker build -t niniko123/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true niniko123/docker-react npm run test -- --coverage
